#!/bin/bash

git clone https://github.com/DaraUng/hello-nti-310

#rsyslog
gcloud compute instances create rsyslog-server \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-b \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=hello-nti-310/rsyslog-server
      
#postgres.sh
gcloud compute instances create postgres \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-b \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=hello-nti-310/postgres.sh

#LDAP-server
gcloud compute instances create nti-310-dara \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-b \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=hello-nti-310/nti-310-dara

#NSF-a
gcloud compute instances create nfs-a \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-b \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=hello-nti-310/nfs_a

#Django
gcloud compute instances create django\
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-b \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=hello-nti-310/django

#LDAP
gcloud compute instances create client-c \
--image-family ubuntu-1804-lts \
--image-project ubuntu-os-cloud \
--zone us-east1-b \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=hello-nti-310/LDAP\ Client\ Automation      


      
#client-b
gcloud compute instances create client-d \
--image-family ubuntu-1804-lts \
--image-project ubuntu-os-cloud \
--zone us-east1-b \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=hello-nti-310/LDAP\ Client\ Automation
