#!/bin/bash

git clone https://github.com/DaraUng/hello-nti-310

echo "creating rsyslog"
#rsyslog
gcloud compute instances create rsyslog-server \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-c \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=hello-nti-310/rsyslog-server

echo "creating postgres"
#postgres.sh
gcloud compute instances create postgres \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-c \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=hello-nti-310/postgres.sh

echo "creating LDAP-server"
#LDAP-server
gcloud compute instances create LDAP-server \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-c \
--tags "http-server","https-server" \
--machine-type f1-micro \cs
--scopes cloud-platform \
--metadata-from-file startup-script=hello-nti-310/LDAP-server

echo "creating nfs-a"
#NSF-a
gcloud compute instances create nfs-a \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-c \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=hello-nti-310/nfs_a

echo "creating django"
#Django
gcloud compute instances create django\
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-c \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=hello-nti-310/django

echo "creating client-c"
#LDAP
gcloud compute instances create client-c \
--image-family ubuntu-1804-lts \
--image-project ubuntu-os-cloud \
--zone us-east1-c \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=hello-nti-310/LDAP\ Client\ Automation      

echo "creating client-d"
      
#client-b
gcloud compute instances create client-d \
--image-family ubuntu-1804-lts \
--image-project ubuntu-os-cloud \
--zone us-east1-c \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=hello-nti-310/LDAP\ Client\ Automation


echo "creating cacti"
#cacti
gcloud compute instances create cacti-install\
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-c \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=hello-nti-310/cacti-install.sh

echo "creating nagios-install"
#nagios
gcloud compute instances create nagios-install\
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-c \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=hello-nti-310/nagios-install

echo "creating nrpe.sh"
#nrpe
gcloud compute instances create nrpe\
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-c \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=hello-nti-310/nrpe.sh
