#!/bin/bash
From the client (ubuntu machine)

apt-get install nfs-client

showmount -e nfs-310-dara
mkdir /mnt/test
echo "nfs-a:/var/nfsshare/testing       /mnt/test   nfs  defaults 0 0" >> /etc/fstab
mount -a

#print ipaddress
